### ISSUE TITLE
Use custom metrics to scale up/down instances

### ISSUE THREAD

**Issue by galindro** [chaordic/tiopatinhas#6]
Is it possible to use cloudwatch custom metrics (like load average) to scale up/down instances?

**Comment by mwconceicao** [comment]
@galindro Better late than never... Tio Patinhas does not use cpu metric anymore (or any cloudwatch metric at all).

**Comment by jdsolucoes** [comment]
So how does tio patinhas knows when to scale up or down?

**Comment by gmendonca** [comment]
I don't know why this was never answered, but tiopatinhas targets the ASG desired capacity to add or remove instances. Therefore it let's the ASG to handle when to reduce the desired capacity or not. Of course that when tiopatinhas adds or remove instances, it will impact the CPU and network of the the ASG's instances. Thus impacting in the ASG actions and allowing the ELB to have desired number of ASG instances and TP instances.
